[package]
name = "living-worlds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
gl = "0.14.0"
glutin = "0.29.1"
json = "0.12.4"
rand = "0.8.5"
