[package]
name = "living-worlds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
json = "0.12.4"
sdl2 = "0.35.2"
